# main text of home
name: Buyuan Zhang
bio: A Girl who travels the world eating noodles

# twitter summary info
description: received the B.S. degree from the Department of Computer Science, Beijing Institute of Technology, Beijing, China, in 2022.
He is currently pursuing the M.S. degree at National Innovation Institute, Academy of Military Sciences, Beijing, China. His research interests include machine learning, signal processing, and human-machine interaction.

picture: assets/images/bio-photo.jpg

url: https://byzhcn.github.io/
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
github: https://github.com/byzhcn
email: byzhcn@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
